authors = {
'Ilhan Omar':'IlhanMN',
'Eugene DePasquale':'DePasqualePA',
'Charles Schumer':'SenSchumer',
'Justice Democrats':'justicedems',
'Arlen Parsa':'arlenparsa',
'Bernie Sanders':'SenSanders',
'Dianne Feinstein':'SenFeinstein',
'Julián Castro':'JulianCastro',
'West Virginia Republican Party':'WVGOP',
'Michael Cohen':'MichaelCohen212',
'Vern Buchanan':'VernBuchanan',
'Tom Cotton':'SenTomCotton',
'Patrick Morrisey':'MorriseyWV',
'Kevin McCarthy':'GOPLeader',
'Grover Norquist':'GroverNorquist',
'Seth Moulton':'sethmoulton',
'Eric Swalwell':'ericswalwell',
'Paul Davis':'pauldavisSNS',
'Eric Cantor':'EricCantor',
'Tulsi Gabbard':'TulsiGabbard',
'Joe Biden':'JoeBiden',
'America First':'AmericaFirstPAC',
'Mike Pence':'Mike_Pence',
'Shannon Watts':'shannonrwatts',
'Justin Amash':'justinamash',
'Washington State Democratic Party':'washdems',
'Debbie Wasserman Schultz':'DWStweets',
'Donald Trump':'realDonaldTrump',
'Joaquin Castro':'JoaquinCastrotx',
'Paul Broun':'PaulBrounMD',
'Mitt Romney':'MittRomney',
'John Boehner':'SpeakerBoehner',
'Candace Owens':'RealCandaceO',
'Ted Cruz':'SenTedCruz',
'Fight for the Future':'fightfortheftr',
'Senate Democrats':'SenateDems',
'David Perdue':'sendavidperdue',
'Alyssa Milano':'Alyssa_Milano',
'Nancy Pelosi':'SpeakerPelosi',
'Tina Smith':'TinaSmithMN',
'Elizabeth Warren':'ewarren',
'Lindsey Graham':'LindseyGrahamSC',
'Everytown for Gun Safety':'Everytown',
'Allen West':'AllenWest',
'Joe Arpaio':'RealSheriffJoe',
'Sean Spicer':'seanspicer',
'Maria Cantwell':'MariaCantwell',
'Amy Klobuchar':'amyklobuchar',
'Jeff Flake':'JeffFlake',
'Tom Colicchio':'tomcolicchio',
'Ron Wyden':'RonWyden',
'Joe Manchin':'Sen_JoeManchin',
'Alexandria Ocasio-Cortez':'AOC',
'Bill Clinton':'BillClinton',
'Jeff Duncan':'JeffDuncan_',
'Sarah Palin':'arahPalinUSA',
'Charlie Kirk':'charliekirk11',
'Chris Murphy':'ChrisMurphyCT',
'Robert Menendez':'SenatorMenendez',
'Hillary Clinton':'HillaryClinton',
'Center for American Progress':'amprog',
'Islamic Republic News Agency':'IrnaEnglish',
'Brad Parscale':'parscale',
'Heritage Foundation':'Heritage',
'Ruben Gallego':'RepRubenGallego',
'Valerie Jarrett':'ValerieJarrett',
'Norm Eisen':'NormEisen',
'Kamala Harris':'KamalaHarris',
'Pete Buttigieg':'PeteButtigieg',
'Claire McCaskill':'clairecmc',
'Good Jobs First':'GoodJobsFirst',
'Anthony Scaramucci':'Scaramucci',
'Howard Dean':'GovHowardDean',
'Keith Ellison':'keithellison',
'Evan Jenkins':'EvanJenkinsWV',
'Ivanka Trump':'IvankaTrump',
'Ro Khanna':'RoKhanna',
'West Virginia Democratic Party':'wvdemocrats',
'Rand Paul':'RandPaul',
'Barack Obama':'BarackObama',
'Republican National Committee':'NRCC',
'Missouri Democratic Party':'MoDemParty',
'Michael Moore':'MMFlint'
}
